/** Declaration file generated by dts-gen */

declare module "circom_tester" {
    export function c(circomInput: any, _options: any): any;

    export function wasm(circomInput: any, _options: any): any;
}
