// https://github.com/weijiekoh/circomlib/blob/feat/poseidon-encryption/
// all credits for this implementation go to https://github.com/weijiekoh

import { Fr } from "@zk-kit/baby-jubjub"

// 2^128 is the largest power of 2 that is less than the alt_bn128 prime order
export const two128 = Fr.e(BigInt("340282366920938463463374607431768211456"))

// Using recommended parameters from whitepaper https://eprint.iacr.org/2019/458.pdf (table 2, table 8)
// Generated by https://extgit.iaik.tugraz.at/krypto/hadeshash/-/blob/master/code/calc_round_numbers.py
// And rounded up to nearest integer that divides by t
export const N_ROUNDS_F = 8
export const N_ROUNDS_P = [56, 57, 56, 60, 60, 63, 64, 63, 60, 66, 60, 65, 70, 60, 64, 68]
